### PR TITLE
LANDIS Disp rewrite with Rcpp

### PR DESCRIPTION
**Pull request by eliotmcintire**

### CODE REVIEW

**Comment by achubaty** [comment]
I see `Namespace dependencies not required: 'R.utils', 'dplyr'` in the error logs of the automated checks.

**Comment by eliotmcintire** [comment]
Because I moved functions from module to package, there were lots of things that were not properly declared/imported. Working through that now. (These are not from the Rcpp stuff; just bycatch of moving module code into a package)

**Comment by eliotmcintire** [comment]
I am unable to debug the windows errors. Not sure what to do about this. It will be on hold for now.

**Comment by achubaty** [comment]
what function being called during tests is the problem?

**Pull request merged**
