### PR TITLE
rm use `NLMR` to generate a random landscape

### PR DESCRIPTION
**Pull request by CeresBarros**
to address https://github.com/PredictiveEcology/LandR/issues/88

### CODE REVIEW

**Comment by achubaty** [comment]
java can be annoying - can we simply `raster::extend()` the resulting raster from the NLMR function? since it's dummy data anyway, we can assign random value to any added cells.

**Comment by achubaty** [comment]
i'd like to implement this approach in the randomLandscapes module in SpaDES.core too

**Comment by CeresBarros** [comment]
I have replaced `rflsgen` with the new `SpaDES.tools` function, `neutralLandscapeMap`, which wraps `NLMR::nlm_mpd` and fixes the missing columns/rowns problem of `NLMR::nlm_mpd`'s output raster. The PR topic was edited accordingly

**Comment by CeresBarros** [comment]
with https://github.com/PredictiveEcology/SpaDES.tools/pull/75

**Comment by CeresBarros** [comment]
passing all CRAN build checks on Windows

**Review by achubaty — APPROVED** [review]
fixed + passing on my end

**Pull request merged**
